
package views.panels.admin;

import views.classes.TableDark;

public class PanelCrudProcesador extends javax.swing.JFrame {
    
    public PanelCrudProcesador() {
        initComponents();
        customInitComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelTitulo1 = new javax.swing.JLabel();
        btnAuriculares = new javax.swing.JButton();
        btnAuriculares1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDark = new javax.swing.JTable();
        btnAuriculares2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        btnAuriculares3 = new javax.swing.JButton();
        btnAuriculares4 = new javax.swing.JButton();
        jLabelTitulo3 = new javax.swing.JLabel();
        jLabelTitulo4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(29, 19, 19));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabelTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo1.setText("Procesadores");
        jPanel2.add(jLabelTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 90));

        btnAuriculares.setBackground(new java.awt.Color(163, 184, 8));
        btnAuriculares.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnAuriculares.setForeground(new java.awt.Color(0, 0, 0));
        btnAuriculares.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.png"))); // NOI18N
        btnAuriculares.setText("Eliminar");
        btnAuriculares.setBorderPainted(false);
        btnAuriculares.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAuriculares.setFocusPainted(false);
        btnAuriculares.setFocusable(false);
        btnAuriculares.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAuriculares.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1-hover.png"))); // NOI18N
        jPanel2.add(btnAuriculares, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 210, 60));

        btnAuriculares1.setBackground(new java.awt.Color(163, 184, 8));
        btnAuriculares1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnAuriculares1.setForeground(new java.awt.Color(0, 0, 0));
        btnAuriculares1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.png"))); // NOI18N
        btnAuriculares1.setText("Actualizar");
        btnAuriculares1.setBorderPainted(false);
        btnAuriculares1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAuriculares1.setFocusPainted(false);
        btnAuriculares1.setFocusable(false);
        btnAuriculares1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAuriculares1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1-hover.png"))); // NOI18N
        jPanel2.add(btnAuriculares1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 210, 60));

        tableDark.setBackground(new java.awt.Color(29, 19, 19));
        tableDark.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descripción", "Precio", "Marca"
            }
        ));
        jScrollPane1.setViewportView(tableDark);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 10, 650, 430));

        btnAuriculares2.setBackground(new java.awt.Color(163, 184, 8));
        btnAuriculares2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnAuriculares2.setForeground(new java.awt.Color(0, 0, 0));
        btnAuriculares2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.png"))); // NOI18N
        btnAuriculares2.setText("Siguiente");
        btnAuriculares2.setBorderPainted(false);
        btnAuriculares2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAuriculares2.setFocusPainted(false);
        btnAuriculares2.setFocusable(false);
        btnAuriculares2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAuriculares2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1-hover.png"))); // NOI18N
        jPanel2.add(btnAuriculares2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 450, 210, 60));

        jTextField2.setBackground(new java.awt.Color(29, 19, 19));
        jTextField2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2.setText("Marca");
        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(163, 184, 8), 2, true));
        jTextField2.setSelectionColor(new java.awt.Color(163, 184, 8));
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 240, 40));

        jTextField3.setBackground(new java.awt.Color(29, 19, 19));
        jTextField3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(153, 153, 153));
        jTextField3.setText("Descripción");
        jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(163, 184, 8), 2, true));
        jTextField3.setSelectionColor(new java.awt.Color(163, 184, 8));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 360, 40));

        jTextField4.setBackground(new java.awt.Color(29, 19, 19));
        jTextField4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(153, 153, 153));
        jTextField4.setText("Precio");
        jTextField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(163, 184, 8), 2, true));
        jTextField4.setSelectionColor(new java.awt.Color(163, 184, 8));
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 110, 40));

        btnAuriculares3.setBackground(new java.awt.Color(163, 184, 8));
        btnAuriculares3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnAuriculares3.setForeground(new java.awt.Color(0, 0, 0));
        btnAuriculares3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.png"))); // NOI18N
        btnAuriculares3.setText("Agregar");
        btnAuriculares3.setBorderPainted(false);
        btnAuriculares3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAuriculares3.setFocusPainted(false);
        btnAuriculares3.setFocusable(false);
        btnAuriculares3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAuriculares3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1-hover.png"))); // NOI18N
        jPanel2.add(btnAuriculares3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 210, 60));

        btnAuriculares4.setBackground(new java.awt.Color(163, 184, 8));
        btnAuriculares4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnAuriculares4.setForeground(new java.awt.Color(0, 0, 0));
        btnAuriculares4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.png"))); // NOI18N
        btnAuriculares4.setText("Anterior");
        btnAuriculares4.setBorderPainted(false);
        btnAuriculares4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAuriculares4.setFocusPainted(false);
        btnAuriculares4.setFocusable(false);
        btnAuriculares4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAuriculares4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1-hover.png"))); // NOI18N
        jPanel2.add(btnAuriculares4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 210, 60));

        jLabelTitulo3.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabelTitulo3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo3.setText("Páginas");
        jPanel2.add(jLabelTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, 100, 30));

        jLabelTitulo4.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabelTitulo4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo4.setText("1 - 1");
        jPanel2.add(jLabelTitulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, 100, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1170, 520));

        jPanel1.setBackground(new java.awt.Color(163, 184, 8));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo2.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTitulo2.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabelTitulo2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo2.setText("Crea tu PC");
        jPanel1.add(jLabelTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 1110, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customInitComponents() {
        jScrollPane1.setViewportView(null);
        
        tableDark = new views.classes.TableDark();
        tableDark.setBackground(new java.awt.Color(29, 19, 19));
        tableDark.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descripción", "Precio", "Marca"
            }
        ));
        
        jScrollPane1.setViewportView(tableDark);
        
        TableDark td = new TableDark();
        
        td.fixTable(jScrollPane1);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelCrudProcesador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelCrudProcesador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelCrudProcesador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelCrudProcesador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelCrudProcesador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAuriculares;
    public javax.swing.JButton btnAuriculares1;
    public javax.swing.JButton btnAuriculares2;
    public javax.swing.JButton btnAuriculares3;
    public javax.swing.JButton btnAuriculares4;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JLabel jLabelTitulo3;
    private javax.swing.JLabel jLabelTitulo4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTable tableDark;
    // End of variables declaration//GEN-END:variables
}
