/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author axelp
 */
public class PanelProcesador extends javax.swing.JFrame {

    /**
     * Creates new form PanelProcesador
     */
    public PanelProcesador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelTitulo2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnMother = new javax.swing.JButton();
        btnMother1 = new javax.swing.JButton();
        jLabelTitulo3 = new javax.swing.JLabel();
        jLabelTitulo4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(163, 184, 8));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo2.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTitulo2.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabelTitulo2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo2.setText("Procesadores");
        jPanel2.add(jLabelTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 140));

        jPanel1.setBackground(new java.awt.Color(29, 19, 19));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, 150, 150));

        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 150, 150));

        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 150, 150));

        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 150, 150));

        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 150, 150));

        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 150, 150));

        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 150, 150));

        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 150, 150));

        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 150, 150));

        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 150, 150));

        btnMother.setBackground(new java.awt.Color(163, 184, 8));
        btnMother.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnMother.setForeground(new java.awt.Color(0, 0, 0));
        btnMother.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.png"))); // NOI18N
        btnMother.setText("Anterior");
        btnMother.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMother.setFocusPainted(false);
        btnMother.setFocusable(false);
        btnMother.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMother.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1-hover.png"))); // NOI18N
        jPanel1.add(btnMother, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 210, 60));

        btnMother1.setBackground(new java.awt.Color(163, 184, 8));
        btnMother1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnMother1.setForeground(new java.awt.Color(0, 0, 0));
        btnMother1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.png"))); // NOI18N
        btnMother1.setText("Siguiente");
        btnMother1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMother1.setFocusPainted(false);
        btnMother1.setFocusable(false);
        btnMother1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMother1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1-hover.png"))); // NOI18N
        jPanel1.add(btnMother1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 210, 60));

        jLabelTitulo3.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabelTitulo3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo3.setText("Páginas");
        jPanel1.add(jLabelTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 170, 30));

        jLabelTitulo4.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabelTitulo4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo4.setText("1 - 1");
        jPanel1.add(jLabelTitulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 170, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 960, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelProcesador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelProcesador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelProcesador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelProcesador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelProcesador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnMother;
    public javax.swing.JButton btnMother1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JLabel jLabelTitulo3;
    private javax.swing.JLabel jLabelTitulo4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
