/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.panels;

/**
 *
 * @author axelp
 */
public class PanelAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form PanelLogin
     */
    public PanelAdministrador() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelTitulo1 = new javax.swing.JLabel();
        btnAuriculares = new javax.swing.JButton();
        btnAuriculares1 = new javax.swing.JButton();
        btnAuriculares2 = new javax.swing.JButton();
        btnAuriculares3 = new javax.swing.JButton();
        btnAuriculares4 = new javax.swing.JButton();
        btnSsd = new javax.swing.JButton();
        btnSsd1 = new javax.swing.JButton();
        btnSsd2 = new javax.swing.JButton();
        btnSsd3 = new javax.swing.JButton();
        btnSsd4 = new javax.swing.JButton();
        btnSsd5 = new javax.swing.JButton();
        btnSsd6 = new javax.swing.JButton();
        btnSsd7 = new javax.swing.JButton();
        btnSsd8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(29, 19, 19));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabelTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo1.setText("Crear, Modificar o Eliminar");
        jPanel2.add(jLabelTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 70));

        btnAuriculares.setBackground(new java.awt.Color(163, 184, 8));
        btnAuriculares.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnAuriculares.setForeground(new java.awt.Color(0, 0, 0));
        btnAuriculares.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.png"))); // NOI18N
        btnAuriculares.setText("Placa de Video");
        btnAuriculares.setBorderPainted(false);
        btnAuriculares.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAuriculares.setFocusPainted(false);
        btnAuriculares.setFocusable(false);
        btnAuriculares.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAuriculares.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1-hover.png"))); // NOI18N
        jPanel2.add(btnAuriculares, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 210, 60));

        btnAuriculares1.setBackground(new java.awt.Color(163, 184, 8));
        btnAuriculares1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnAuriculares1.setForeground(new java.awt.Color(0, 0, 0));
        btnAuriculares1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.png"))); // NOI18N
        btnAuriculares1.setText("Procesador");
        btnAuriculares1.setBorderPainted(false);
        btnAuriculares1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAuriculares1.setFocusPainted(false);
        btnAuriculares1.setFocusable(false);
        btnAuriculares1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAuriculares1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1-hover.png"))); // NOI18N
        jPanel2.add(btnAuriculares1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 210, 60));

        btnAuriculares2.setBackground(new java.awt.Color(163, 184, 8));
        btnAuriculares2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnAuriculares2.setForeground(new java.awt.Color(0, 0, 0));
        btnAuriculares2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.png"))); // NOI18N
        btnAuriculares2.setText("Mother");
        btnAuriculares2.setBorderPainted(false);
        btnAuriculares2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAuriculares2.setFocusPainted(false);
        btnAuriculares2.setFocusable(false);
        btnAuriculares2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAuriculares2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1-hover.png"))); // NOI18N
        jPanel2.add(btnAuriculares2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 210, 60));

        btnAuriculares3.setBackground(new java.awt.Color(163, 184, 8));
        btnAuriculares3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnAuriculares3.setForeground(new java.awt.Color(0, 0, 0));
        btnAuriculares3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.png"))); // NOI18N
        btnAuriculares3.setText("Cooler");
        btnAuriculares3.setBorderPainted(false);
        btnAuriculares3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAuriculares3.setFocusPainted(false);
        btnAuriculares3.setFocusable(false);
        btnAuriculares3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAuriculares3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1-hover.png"))); // NOI18N
        jPanel2.add(btnAuriculares3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 210, 60));

        btnAuriculares4.setBackground(new java.awt.Color(163, 184, 8));
        btnAuriculares4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnAuriculares4.setForeground(new java.awt.Color(0, 0, 0));
        btnAuriculares4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.png"))); // NOI18N
        btnAuriculares4.setText("Memoria RAM");
        btnAuriculares4.setBorderPainted(false);
        btnAuriculares4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAuriculares4.setFocusPainted(false);
        btnAuriculares4.setFocusable(false);
        btnAuriculares4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAuriculares4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1-hover.png"))); // NOI18N
        jPanel2.add(btnAuriculares4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 210, 60));

        btnSsd.setBackground(new java.awt.Color(163, 184, 8));
        btnSsd.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnSsd.setForeground(new java.awt.Color(0, 0, 0));
        btnSsd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.png"))); // NOI18N
        btnSsd.setText("Auriculares");
        btnSsd.setBorderPainted(false);
        btnSsd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSsd.setFocusPainted(false);
        btnSsd.setFocusable(false);
        btnSsd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSsd.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1-hover.png"))); // NOI18N
        jPanel2.add(btnSsd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 210, 60));

        btnSsd1.setBackground(new java.awt.Color(163, 184, 8));
        btnSsd1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnSsd1.setForeground(new java.awt.Color(0, 0, 0));
        btnSsd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.png"))); // NOI18N
        btnSsd1.setText("Disco Solido");
        btnSsd1.setBorderPainted(false);
        btnSsd1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSsd1.setFocusPainted(false);
        btnSsd1.setFocusable(false);
        btnSsd1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSsd1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1-hover.png"))); // NOI18N
        jPanel2.add(btnSsd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 210, 60));

        btnSsd2.setBackground(new java.awt.Color(163, 184, 8));
        btnSsd2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnSsd2.setForeground(new java.awt.Color(0, 0, 0));
        btnSsd2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.png"))); // NOI18N
        btnSsd2.setText("Fuente");
        btnSsd2.setBorderPainted(false);
        btnSsd2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSsd2.setFocusPainted(false);
        btnSsd2.setFocusable(false);
        btnSsd2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSsd2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1-hover.png"))); // NOI18N
        jPanel2.add(btnSsd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 210, 60));

        btnSsd3.setBackground(new java.awt.Color(163, 184, 8));
        btnSsd3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnSsd3.setForeground(new java.awt.Color(0, 0, 0));
        btnSsd3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.png"))); // NOI18N
        btnSsd3.setText("Gabinete");
        btnSsd3.setBorderPainted(false);
        btnSsd3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSsd3.setFocusPainted(false);
        btnSsd3.setFocusable(false);
        btnSsd3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSsd3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1-hover.png"))); // NOI18N
        jPanel2.add(btnSsd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 210, 60));

        btnSsd4.setBackground(new java.awt.Color(163, 184, 8));
        btnSsd4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnSsd4.setForeground(new java.awt.Color(0, 0, 0));
        btnSsd4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.png"))); // NOI18N
        btnSsd4.setText("Teclado");
        btnSsd4.setBorderPainted(false);
        btnSsd4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSsd4.setFocusPainted(false);
        btnSsd4.setFocusable(false);
        btnSsd4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSsd4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1-hover.png"))); // NOI18N
        jPanel2.add(btnSsd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 210, 60));

        btnSsd5.setBackground(new java.awt.Color(163, 184, 8));
        btnSsd5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnSsd5.setForeground(new java.awt.Color(0, 0, 0));
        btnSsd5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.png"))); // NOI18N
        btnSsd5.setText("Monitor");
        btnSsd5.setBorderPainted(false);
        btnSsd5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSsd5.setFocusPainted(false);
        btnSsd5.setFocusable(false);
        btnSsd5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSsd5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1-hover.png"))); // NOI18N
        jPanel2.add(btnSsd5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 210, 60));

        btnSsd6.setBackground(new java.awt.Color(163, 184, 8));
        btnSsd6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnSsd6.setForeground(new java.awt.Color(0, 0, 0));
        btnSsd6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.png"))); // NOI18N
        btnSsd6.setText("Mouse");
        btnSsd6.setBorderPainted(false);
        btnSsd6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSsd6.setFocusPainted(false);
        btnSsd6.setFocusable(false);
        btnSsd6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSsd6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1-hover.png"))); // NOI18N
        jPanel2.add(btnSsd6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 210, 60));

        btnSsd7.setBackground(new java.awt.Color(163, 184, 8));
        btnSsd7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnSsd7.setForeground(new java.awt.Color(0, 0, 0));
        btnSsd7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.png"))); // NOI18N
        btnSsd7.setText("Disco Rigido");
        btnSsd7.setBorderPainted(false);
        btnSsd7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSsd7.setFocusPainted(false);
        btnSsd7.setFocusable(false);
        btnSsd7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSsd7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1-hover.png"))); // NOI18N
        jPanel2.add(btnSsd7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 210, 60));

        btnSsd8.setBackground(new java.awt.Color(163, 184, 8));
        btnSsd8.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnSsd8.setForeground(new java.awt.Color(0, 0, 0));
        btnSsd8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.png"))); // NOI18N
        btnSsd8.setText("Mouse Pad");
        btnSsd8.setBorderPainted(false);
        btnSsd8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSsd8.setFocusPainted(false);
        btnSsd8.setFocusable(false);
        btnSsd8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSsd8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1-hover.png"))); // NOI18N
        jPanel2.add(btnSsd8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 210, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 500, 570));

        jPanel1.setBackground(new java.awt.Color(163, 184, 8));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo2.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTitulo2.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabelTitulo2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo2.setText("Administrador");
        jPanel1.add(jLabelTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAuriculares;
    public javax.swing.JButton btnAuriculares1;
    public javax.swing.JButton btnAuriculares2;
    public javax.swing.JButton btnAuriculares3;
    public javax.swing.JButton btnAuriculares4;
    public javax.swing.JButton btnSsd;
    public javax.swing.JButton btnSsd1;
    public javax.swing.JButton btnSsd2;
    public javax.swing.JButton btnSsd3;
    public javax.swing.JButton btnSsd4;
    public javax.swing.JButton btnSsd5;
    public javax.swing.JButton btnSsd6;
    public javax.swing.JButton btnSsd7;
    public javax.swing.JButton btnSsd8;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
